# Generated by Django 3.2 on 2021-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybank', '0003_auto_20210520_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='from_accno',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
